config/routes.rb
Tsubuyaki2nd::Application.routes.draw do
  devise_for :users
  resources :tweets do
    post :favorite
  end

  root to: 'tweets#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :tweet_id, :user_id
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :content
  default_scope order('created_at DESC')
  belongs_to :user
  has_many :favorites
  validates_associated :user
  validates :content, presence: true, length: { in: 1..140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :tweets
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  # def show
    # @tweet = Tweet.find(params[:id])

    # respond_to do |format|
      # format.html # show.html.erb
      # format.json { render json: @tweet }
    # end
  # end

  # GET /tweets/new
  # GET /tweets/new.json
  # def new
    # @tweet = Tweet.new

    # respond_to do |format|
      # format.html # new.html.erb
      # format.json { render json: @tweet }
    # end
  # end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html do
          @tweets = Tweet.all
          render actionn: "index"
        end
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tsubuyaki2nd</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<hr>

<% if user_signed_in? %>
  <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
<% end %>

</body>
</html>

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
%h1 Listing tweets

= render 'form'

%table
  %tr
    %th User
    %th Content
    %th
    %th
    %th

  - @tweets.each do |tweet|
    %tr
      %td= tweet.user_id
      %td= tweet.content
      %td= link_to 'Show', tweet
      %td= link_to 'Edit', edit_tweet_path(tweet)
      %td= link_to 'Destroy', tweet_path(tweet), :action => "delete"